/*
 * Copyright (C) 2017-2026 Fredrik Öhrström (gpl-3.0-or-later)
 * Copyright (C) 2026 Metbox / @metbox/wmbus contributors (gpl-3.0-or-later)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
// Auto-generated by scripts/generate-manufacturers.ts — do not edit by hand.
// Source: vendor/wmbusmeters@af48083/src/manufacturers.h
//
// Maps 16-bit manufacturer codes (MANFCODE packing of 3 upper-case letters) to
// the human-readable name upstream wmbusmeters assigns. The 3-letter flag can
// be computed directly from the code — see `manufacturerFlag()` in manufacturers.ts.

export const MANUFACTURER_NAMES: Readonly<Record<number, string>> = Object.freeze({
  1057: "Aventies, Germany", // AAA
  1058: "Milas", // AAB
  1090: "ABB, Sweden", // ABB
  1091: "Paya Energy", // ABC
  1102: "ABN Braun, Germany", // ABN
  1106: "ABB, Czech Republic", // ABR
  1121: "Acean, France", // ACA
  1122: "AcBel Polytech, Taiwan", // ACB
  1123: "Accurate, Pakistan", // ACC
  1125: "Actaris Electricity, France", // ACE
  1127: "Actaris Gas, France", // ACG
  1128: "Acantho, Italy", // ACH
  1132: "Aclara Meters UK, United Kingdom", // ACL
  1134: "ACN Advanced Communications Networks, Switzerland", // ACN
  1139: "Tianjin Chuangshi Technology Developing, China", // ACS
  1140: "Activis Metering, Germany", // ACT
  1143: "Actaris Water and Heat, France", // ACW
  1153: "Andrea Informatique, France", // ADA
  1156: "ADD Production, Moldova", // ADD
  1157: "Yantai Aerospace Delu Energy saving Technology, China", // ADE
  1158: "ADFweb com, Italy", // ADF
  1166: "Aidon, Finland", // ADN
  1170: "Adrem Engineering, Romania", // ADR
  1173: "Adunos, Germany", // ADU
  1174: "Advant", // ADV
  1176: "ADD Production, Moldova", // ADX
  1185: "Abam Electronic Alborz, Iran", // AEA
  1187: "Advance Electronics Company, Saudi Arabia", // AEC
  1189: "Atlas Electronics, Serbia", // AEE
  1191: "AEG", // AEG
  1193: "Ajay Electrical Industries, India", // AEI
  1196: "Kohler, Turkey", // AEL
  1197: "S C AEM, Romania", // AEM
  1198: "ADVANCED ENERGY MANAGEMENT SOLUTIONS, Nigeria", // AEN
  1202: "Aerzener Maschinenfabrik, Germany", // AER
  1203: "ALFANAR ELECTRICAL SYSTEM, Saudi Arabia", // AES
  1235: "AFSONA INVEST, Uzbekistan", // AFS
  1240: "Alflex Products, Netherlands", // AFX
  1253: "AccessGate, Sweden", // AGE
  1257: "PT Armitec Electrical Systems, Indonesia", // AGI
  1268: "Agnitio Technologies, India", // AGT
  1302: "aventies, Germany", // AHV
  1304: "Sepanta Electronic Tabarestan, Iran", // AHX
  1315: "Avastu Creations, India", // AIC
  1325: "Ningbo Aimei Meter Manufacture, China", // AIM
  1387: "MAximum, Moldova", // AKK
  1397: "Akanksha Power and Infrastructure, India", // AKU
  1411: "Zenner Gas, Italy", // ALC
  1413: "AEROSPACE LIANGLI ELECTRIC, China", // ALE
  1414: "Alfatech Elektromed Elektronik, Turkey", // ALF
  1415: "Algodue Elettronica, Italy", // ALG
  1416: "ALFANAR ELECTRICAL SYSTEM, Saudi Arabia", // ALH
  1419: "Actislink, Poland", // ALK
  1420: "Allied Engineering Works, India", // ALL
  1424: "Alphion, India", // ALP
  1426: "Algorab, Italy", // ALR
  1428: "Amplitec, Germany", // ALT
  1430: "Alvicom, Hungary", // ALV
  1442: "Wurth Elektronik eiSos, Germany", // AMB
  1443: "Arch Meter Corporation, Taiwan", // AMC
  1444: "KEPID AMSTECH, South Korea", // AMD
  1445: "Avon Meters, India", // AME
  1447: "ANTE METER GROUP, China", // AMG
  1448: "AmiHo, United Kingdom", // AMH
  1449: "AMI Tech I, India", // AMI
  1452: "Eon Electric, India", // AML
  1456: "Ampy Automation Digilog", // AMP
  1458: "Actislink, Poland", // AMR
  1459: "Zhejiang Joy Electronic Technology, China", // AMS
  1460: "INTEGRA METERING", // AMT
  1464: "APATOR METRIX, Poland", // AMX
  1473: "Anacle Systems, Singapore", // ANA
  1476: "Andis, Slovakia", // AND
  1477: "AN electronic, Czech Republic", // ANE
  1498: "Anhui Nari Zenith Electricity Electronic", // ANZ
  1517: "Aquametro Oil Marine, Switzerland", // AOM
  1518: "ASTRON, Slovenia", // AON
  1537: "Apator, Poland", // APA
  1548: "APLI, Slovakia", // APL
  1551: "Apolis, Germany", // APO
  1554: "Apronecs, Bulgaria", // APR
  1555: "Apsis Kontrol Sistemleri, Turkey", // APS
  1556: "Apator, Poland", // APT
  1560: "Amplex, Denmark", // APX
  1569: "ACTAQUA, Germany", // AQA
  1580: "Aqualoc, South Africa", // AQL
  1581: "INTEGRA METERING, Switzerland", // AQM
  1582: "Aquantia, Italy", // AQN
  1588: "Aquatherm PPH, Poland", // AQT
  1589: "Aquamess, Germany", // AQU
  1601: "Aranha, United Kingdom", // ARA
  1603: "Arcelik, Turkey", // ARC
  1604: "Arad Group, Israel", // ARD
  1606: "ADEUNIS RF, France", // ARF
  1607: "ARGO group of companies, Russian Federation", // ARG
  1608: "PT Armitec Electrical Systems, Indonesia", // ARH
  1611: "Arkon Flow Systems, Czech Republic", // ARK
  1613: "Arivus metering, Germany", // ARM
  1617: "ARQIVA, United Kingdom", // ARQ
  1619: "ADD, Bulgaria", // ARS
  1620: "Electrotecnica Arteche Smart Grid, Spain", // ART
  1623: "Arrow Electronics, India", // ARW
  1624: "Aras Mercu Sdn Bhd, Malaysia", // ARX
  1633: "Asac, Italy", // ASA
  1635: "A2A Smart City, Italy", // ASC
  1636: "AS DAQ SYSTEMS, India", // ASD
  1639: "Meter technology Company, Saudi Arabia", // ASG
  1640: "Basic Electronics Company, Saudi Arabia", // ASH
  1642: "ACCUMET SOLUTIONS, India", // ASJ
  1645: "Adya Wifi Metering, India", // ASM
  1650: "Erelsan Elektrik ve Elektronik, Turkey", // ASR
  1652: "ASTINCO, Canada", // AST
  1657: "Arvato Systems Digital, Germany", // ASY
  1665: "Alcansar OElcum ve Otomasyon Sistemleri, Turkey", // ATA
  1669: "ADVANCE TECHNOLOGY AND ELECTRICS COMPANY LIMTED, Thailand", // ATE
  1670: "AKTIF OTOMASYON STI, Turkey", // ATF
  1673: "Analogics Tech, India", // ATI
  1676: "Atlas Elektronik, Turkey", // ATL
  1677: "Atmel SAU, Spain", // ATM
  1683: "Atlas Sayac Sanayi, Turkey", // ATS
  1714: "Aurum Europe, Netherlands", // AUR
  1716: "Aiut, Poland", // AUT
  1720: "Ningbo Sanxing Smart Electric, China", // AUX
  1729: "Avangard JSC, Russian Federation", // AVA
  1733: "ASHTAVINAYAKA ENERGY INFRA, India", // AVE
  1801: "Axioma Metering UAB, Lithuania", // AXI
  1811: "AXSEM, Switzerland", // AXS
  1843: "Euromet Stl, Turkey", // AYS
  1861: "AZEL Electronics, Turkey", // AZE
  2093: "Bachmann, Germany", // BAM
  2098: "Baer Industrie Elektronik, Germany", // BAR
  2099: "BASIC INTELLIGENCE TECHNOLOGY, China", // BAS
  2117: "Bentec Bhartia Engineers, India", // BBE
  2131: "BBS Electronics, Singapore", // BBS
  2149: "ShenZhen B C Electronic, China", // BCE
  2162: "Jiangsu Bingchen Electronics, China", // BCR
  2209: "Baer Energy Automation, Germany", // BEA
  2213: "Bentec, India", // BEE
  2214: "BEFEGA, Germany", // BEF
  2215: "begcomm Communication, Sweden", // BEG
  2220: "Belassitsa AD, Bulgaria", // BEL
  2222: "BEENIC, Germany", // BEN
  2226: "Bernina Electronic, Switzerland", // BER
  2263: "BFW Buero fuer Waermemesstechnik OHG, Germany", // BFW
  2311: "Brunata, Denmark", // BHG
  2349: "BEAM INFOTECH, India", // BIM
  2393: "Beijing JOYO smart water meter, China", // BJY
  2402: "Boendekomfort, Sweden", // BKB
  2415: "Beko Elektronik, Turkey", // BKO
  2420: "Bekto Precisa, Bosnia and Herzegovina", // BKT
  2445: "BELIMO Automation, Switzerland", // BLM
  2453: "Bluering, Italy", // BLU
  2469: "Beifeng, Germany", // BME
  2473: "Badger Meter, United States of America", // BMI
  2480: "BMETERS Polska, Poland", // BMP
  2484: "BMETERS, Italy", // BMT
  2514: "Beijing Banner Electric, China", // BNR
  2550: "JiaXing Bove Intelligent Technology, China", // BOV
  2573: "Aadharshila Mobility Solutions, India", // BPM
  2625: "Brandes, Germany", // BRA
  2627: "BRICK4U, Germany", // BRC
  2638: "Bruntab Energy, Iran", // BRN
  2644: "BEREKET TEKNOLOJIK OELCUM SISTEMLERI BIL ELK INS ITH IHR SAN VE TIC STI, Turkey", // BRT
  2645: "Klaus Bruchmann, Germany", // BRU
  2659: "Sanaye Sanjesh Energy Behineh Sazan Toos, Iran", // BSC
  2660: "BSED, Germany", // BSD
  2661: "Basari Elektronik, Turkey", // BSE
  2665: "Bundesamt fur Sicherheit in der Informationstechnik BSI, Germany", // BSI
  2669: "Bluestar Electrical Meter Research Institute, China", // BSM
  2672: "Byucksan Power, South Korea", // BSP
  2675: "Baylan Su Sayaclari, Turkey", // BSS
  2676: "BESTAS Elektronik Optik, Turkey", // BST
  2680: "BS Messtechnik, Germany", // BSX
  2681: "Aktif Enerji AE nsaat Sanayi ve Ticaret Sirketi, Turkey", // BSY
  2689: "Buta Elektromekanik, Turkey", // BTA
  2700: "BIT LAB", // BTL
  2701: "Bharatech Smart Industrial, India", // BTM
  2706: "RIA BTR Produktions, Germany", // BTR
  2707: "Basari Teknolojik Sistemler, Turkey", // BTS
  2738: "Bopp und Reuther Messtechnik, Germany", // BUR
  2745: "BUYI TECHNOLOGOY, China", // BUY
  2819: "Beijing Fuxing Xiao Cheng Electronic Technology Stock Xisanhuan Beilu, China", // BXC
  2852: "BYD Company, China", // BYD
  2860: "Baylan, Turkey", // BYL
  2871: "Baylan Water Meters, Turkey", // BYW
  2898: "Gebr Bauer, Germany", // BZR
  3106: "Cabtronix, Switzerland", // CAB
  3108: "CADIS, Belgium", // CAD
  3112: "MAEC GROUPE CAHORS, France", // CAH
  3116: "Caleffi, Italy", // CAL
  3118: "PT CANNET ELEKTRIK, Indonesia", // CAN
  3122: "CARI Electronic, France", // CAR
  3124: "Cubes And Tubes, Finland", // CAT
  3126: "CaveTronic, Poland", // CAV
  3142: "ELECTRICAL CIRCUIT BREAKER FACTORY FOR INDUSTRY ECB, Saudi Arabia", // CBF
  3145: "Circuit Breaker Industries, South Africa", // CBI
  3155: "CB Svendsen, Denmark", // CBS
  3184: "1334816, Canada", // CCP
  3187: "Chetas Control Systems, India", // CCS
  3201: "Centre for Development of Advanced Computing, India", // CDA
  3212: "Customised Data, United Kingdom", // CDL
  3220: "CENTRE FOR DEVELOPMENT OF TELEMATICS, India", // CDT
  3234: "Cebyc, Norway", // CEB
  3236: "CEDARNET, France", // CED
  3239: "Consolinno Energy, Germany", // CEG
  3240: "Tosee Garan Sanjesh Energy Hoshmand, Iran", // CEH
  3244: "Creative Electronics, Pakistan", // CEL
  3245: "YAVUZ METAL SANAYI VE TICARET, Turkey", // CEM
  3252: "Cetinkaya Aydinlatma, Turkey", // CET
  3299: "Contor Group, Romania", // CGC
  3311: "Cavagna Group, Italy", // CGO
  3329: "Charles Technology Research, Taiwan", // CHA
  3331: "CHUN IL INSTRUMENT, South Korea", // CHC
  3333: "Shandong Chenhui Electronic Technology, China", // CHE
  3341: "Chung Hsin Electric and Machinery Manufacturing, Taiwan", // CHM
  3347: "Smart Services International, Switzerland", // CHS
  3363: "CHALLENGE INDUSTRIAL, Taiwan", // CIC
  3378: "Circutor, Spain", // CIR
  3411: "CJS Technology, United Kingdom", // CJS
  3444: "CKT Elektrik Elektronik Sanayi ve Ticaret, Turkey", // CKT
  3457: "3g celllabs, India", // CLA
  3458: "CMC, Italy", // CLB
  3461: "Shen Zhen Clou Electronics, China", // CLE
  3471: "Clorius Raab Karcher Energi Service", // CLO
  3475: "Celsa Messgeraete, Germany", // CLS
  3476: "Zhuhai S E Z Calintech Electric, China", // CLT
  3480: "CLK IPEKYOLU LOJISTIK VE TICARET A AA, Turkey", // CLX
  3481: "Clayster, Sweden", // CLY
  3491: "CMC EKOCON, Slovenia", // CMC
  3504: "CM Partner, South Korea", // CMP
  3507: "CMS Computers", // CMS
  3508: "CMOSTEK MICROELECTRONICS, China", // CMT
  3510: "Comverge, United States of America", // CMV
  3533: "COSTEL, South Korea", // CNM
  3541: "CNU Global, South Korea", // CNU
  3560: "COHEAT Future Business Centre, United Kingdom", // COH
  3565: "COMMON, Poland", // COM
  3566: "Conlog", // CON
  3591: "CentraPlus, Germany", // CPG
  3596: "CPL CONCORDIA Soc Coop, Italy", // CPL
  3599: "C3PO, Spain", // CPO
  3603: "CAPITAL POWER SYSTEMS, India", // CPS
  3619: "Yueqing Qicheng Electric, China", // CQC
  3652: "CRDM DEVELOPPEMENTS, France", // CRD
  3668: "CRDM Technology, France", // CRT
  3671: "Xuzhou Runwu Science and Technology Development, China", // CRW
  3672: "Corinex Communications, Canada", // CRX
  3673: "Crystal Power, India", // CRY
  3683: "CHUBUSEIKI, Japan", // CSC
  3692: "Comsel System, Finland", // CSL
  3696: "CSP Innovazione nelle ICT, Italy", // CSP
  3703: "Critical Software, Portugal", // CSW
  3717: "COSTER T E, Italy", // CTE
  3724: "Cyan Technology, United Kingdom", // CTL
  3728: "Cabcon Technologies, India", // CTP
  3729: "Control Q, Netherlands", // CTQ
  3730: "Contar Electronica Industrial, Portugal", // CTR
  3732: "DLMS User Association Conformance, Switzerland", // CTT
  3736: "Contronix, Germany", // CTX
  3746: "Cubic Sensor and Instrument, China", // CUB
  3747: "Cuculus, Germany", // CUC
  3762: "CURRENT Group, United States of America", // CUR
  3809: "CompWell, Sweden", // CWA
  3817: "Cewe Instrument, Sweden", // CWI
  3830: "CMEC Electric Import Export, China", // CWV
  3877: "Quanzhou Chiyoung Electronics Technology, China", // CYE
  3881: "QUANZHOU CHIYOUNG INSTRUMENT, China", // CYI
  3886: "Cynox Weinart Engineering, Germany", // CYN
  3905: "Contadores de Agua de Zaragoza, Spain", // CZA
  3917: "Cazzaniga", // CZM
  4133: "DAE, Italy", // DAE
  4134: "Daf Enerji Sanayi ve Ticaret, Turkey", // DAF
  4142: "Danubia", // DAN
  4164: "DBD Water Systems, India", // DBD
  4165: "Decibels Electronics P Decibels Electronics, India", // DBE
  4196: "Delhi Control Devices, India", // DCD
  4207: "diaeco wave company, Iran", // DCO
  4218: "decarbon, Germany", // DCZ
  4229: "D D Elettronica, Italy", // DDE
  4233: "DD Infraventures, India", // DDI
  4236: "DONGDO LMS, South Korea", // DDL
  4257: "Dea HT, Italy", // DEA
  4259: "DECODE Data Communications, Serbia", // DEC
  4265: "DevSys Embedded Technology, India", // DEI
  4268: "DELTAMESS DWWF, Germany", // DEL
  4270: "Ducati Energia, Italy", // DEN
  4275: "Desi Alarms, Turkey", // DES
  4278: "Develco Products, Denmark", // DEV
  4293: "Dongfang Electronics, China", // DFE
  4307: "Danfoss", // DFS
  4323: "Digicom, Italy", // DGC
  4329: "Digi International", // DGI
  4333: "Diehl Metering, Germany", // DGM
  4345: "Discovergy, Germany", // DGY
  4353: "Shanghai dahua measuring auto control instruments manufactory, China", // DHA
  4369: "YIDU Smart Technology Beijing, China", // DHQ
  4389: "Dielen, Germany", // DIE
  4391: "Digutal Request, Germany", // DIG
  4396: "DECCAN INFRATECH LIMETED, India", // DIL
  4417: "De Jaeger Automation, Belgium", // DJA
  4473: "Electric Power Research Institute of Guangdong Power Grid Corporation, China", // DKY
  4504: "Delixi Group Instruments Meters, China", // DLX
  4515: "DMC International, United Arab Emirates", // DMC
  4517: "DIEHL Metering, Germany", // DME
  4519: "DIINNO, Germany", // DMG
  4521: "Dualmicro Measurement Technologies, Netherlands", // DMI
  4527: "BEENIC, Germany", // DMO
  4528: "DM Power, South Korea", // DMP
  4531: "Digilog Micro Solutions, India", // DMS
  4546: "Dana Sanjesh o Bargh Danaab, Iran", // DNB
  4547: "Dongnam, South Korea", // DNC
  4559: "DENO, Croatia", // DNO
  4564: "Dr Neuhaus Telekommunikation, Germany", // DNT
  4566: "DNV GL, Netherlands", // DNV
  4586: "Suzhou Dojustek Intelligent Technology, China", // DOJ
  4589: "Domat Control System, Czech Republic", // DOM
  4595: "Metsec Cables, Kenya", // DOS
  4621: "DELTA PRIMA METERING SDN BHD", // DPM
  4624: "DECCAN POWER PRODUCTS, India", // DPP
  4675: "DURECOM, South Korea", // DRC
  4688: "DBD WATER SYSTEMS, India", // DRP
  4692: "DRESSER Italia, Italy", // DRT
  4709: "Digitech Systems and Engineering, India", // DSE
  4717: "Desimal Elektronik Muhendislik San ve Tic, Turkey", // DSM
  4724: "Shenzhen Donsun Technology, China", // DST
  4741: "DanTaet, Denmark", // DTE
  4769: "DLMS User Association, Switzerland", // DUA
  4787: "Dresser Utility Solutions, Germany", // DUS
  4805: "DEV ENERGY, Morocco", // DVE
  4807: "Device, Germany", // DVG
  4812: "devolo, Germany", // DVL
  4857: "Dwyer Instruments, United States of America", // DWY
  4858: "Lorenz, Germany", // DWZ
  4935: "DZG Metering, Germany", // DZG
  5153: "Electronic Afzar Azma, Iran", // EAA
  5156: "EAD Energieabrechnungssysteme", // EAD
  5160: "Endress Hauser, Germany", // EAH
  5171: "EAS Elektronik San Tic, Turkey", // EAS
  5189: "Ebeco, Sweden", // EBE
  5195: "Biesenthal, Germany", // EBK
  5206: "EBV Elektronik, Germany", // EBV
  5210: "eBZ, Germany", // EBZ
  5217: "ECO ADAPT, France", // ECA
  5218: "ELECTRICAL CIRCUITT BREAKER FACTORY FOR INDUSTRY, Saudi Arabia", // ECB
  5219: "Energycare Company, Saudi Arabia", // ECC
  5224: "Networked Energy Services Corporation, United States of America", // ECH
  5225: "ECIL, India", // ECI
  5228: "Electronics Corporation of, India", // ECL
  5229: "Ecomess, Poland", // ECM
  5231: "Engie BtoC Smart program, France", // ECO
  5235: "Herholdt Controls, Italy", // ECS
  5257: "Enel Distribuzione Via Ombrone, Italy", // EDI
  5261: "EDMI", // EDM
  5264: "Electro Digital Meter Project Management Services, United Arab Emirates", // EDP
  5283: "ESCO, Poland", // EEC
  5285: "3E, Italy", // EEE
  5289: "ELSOURCE, India", // EEI
  5293: "Electrify Energy, India", // EEM
  5295: "Eppeltone Engineers, India", // EEO
  5296: "ELECTRONET EQUIPMENT, India", // EEP
  5299: "Eletra Industria e Comercio de Medidores Eletricos, Brazil", // EES
  5313: "EFACEC Engenharia e Sistemas, Portugal", // EFA
  5317: "Engelmann Sensor, Germany", // EFE
  5321: "Efimatic Iberica, Spain", // EFI
  5326: "EFEN, Germany", // EFN
  5330: "Europaeische Funk Rundsteuerung, Germany", // EFR
  5331: "EFSYS, France", // EFS
  5345: "eGain International, Sweden", // EGA
  5347: "Ekbatan Gas Control, Iran", // EGC
  5348: "EcoGuard, Sweden", // EGD
  5357: "Elgama Elektronika, Lithuania", // EGM
  5364: "Enegate, Japan", // EGT
  5367: "Enermess Energie Mess und Servicedienste, Germany", // EGW
  5369: "ian Smart Meter Company, Egypt", // EGY
  5388: "Secure Meters", // EHL
  5395: "Endress Hauser SICK, Germany", // EHS
  5413: "Ei Electronics, Ireland", // EIE
  5415: "Eigensonne, Germany", // EIG
  5424: "Elmeasure, India", // EIP
  5428: "EnergyICT, Belgium", // EIT
  5473: "Eka Systems, United States of America", // EKA
  5478: "EKF, Russian Federation", // EKF
  5487: "EKOLIS, France", // EKO
  5491: "DICLE KOEK ENERJI YATIRIM", // EKS
  5492: "PA KVANT J S, Russian Federation", // EKT
  5507: "CJSC EMIS, Russian Federation", // ELC
  5508: "Elektromed Elektronik, Turkey", // ELD
  5509: "Elster Electricity, United States of America", // ELE
  5511: "Elgas, Czech Republic", // ELG
  5516: "Energy Plus, Russian Federation", // ELL
  5517: "Elektromed Elektronik, Turkey", // ELM
  5519: "ELO Sistemas Eletronicos, Brazil", // ELO
  5520: "ElectroPlus, Iran", // ELP
  5521: "ELEQ, Germany", // ELQ
  5522: "Elster Metering, United Kingdom", // ELR
  5523: "Elster, Germany", // ELS
  5524: "ELTAKO, Germany", // ELT
  5526: "Elvaco, Sweden", // ELV
  5529: "Elektroniksystem i Umeaa, Sweden", // ELY
  5538: "Embit, Italy", // EMB
  5539: "Embedded Communication Systems, Switzerland", // EMC
  5541: "SC Electromagnetica, Romania", // EME
  5542: "IT Beratung Energiemanagement Flammang, Germany", // EMF
  5544: "EMH metering formerly EMH Elektrizitatszahler", // EMH
  5545: "Entorno Inteligente de Medicion, Spain", // EMI
  5548: "Emlite, United Kingdom", // EML
  5549: "Email Metering, Australia", // EMM
  5551: "Enermet", // EMO
  5554: "CJSC Energomera, Russian Federation", // EMR
  5555: "EMS PATVAG, Switzerland", // EMS
  5556: "Elster Messtechnik, Germany", // EMT
  5557: "EMU Elektronik, Switzerland", // EMU
  5571: "ENSYCO ETHIOPIA ELECTRICITY METER MANUFACTURING, China", // ENC
  5572: "ENDYS", // END
  5573: "ENERDIS, France", // ENE
  5575: "ENER G Switch, United Kingdom", // ENG
  5576: "ENMAS, Germany", // ENH
  5577: "entec innovations, Germany", // ENI
  5580: "ENEL, Serbia", // ENL
  5582: "Enernet, South Korea", // ENN
  5583: "ennovatis, Germany", // ENO
  5584: "Kiev Polytechnical Scientific Research", // ENP
  5586: "Energisme", // ENR
  5587: "ENSO NETZ, Germany", // ENS
  5588: "ENTES Elektronik, Turkey", // ENT
  5592: "Enetronx, Germany", // ENX
  5641: "EPI USE AFRICA, South Africa", // EPI
  5644: "Escorts, Pakistan", // EPL
  5652: "Energy Prospect Technologies, Spain", // EPT
  5701: "Enermatics Energy, South Africa", // ERE
  5705: "Easun Reyrolle, India", // ERI
  5708: "Erelsan Elektrik ve Elektronik, Turkey", // ERL
  5710: "Ericsson Telecomunicazioni, Italy", // ERN
  5715: "Eurosys, Bulgaria", // ERS
  5719: "Everrenew Energy, India", // ERW
  5729: "ESAC, Italy", // ESA
  5731: "EDMI Shenzhen, China", // ESC
  5732: "Edelstrom Electronic Devices and Designing, United Arab Emirates", // ESD
  5733: "ESE Nordic, Sweden", // ESE
  5735: "ESG, South Korea", // ESG
  5736: "EMSYCON, Germany", // ESH
  5737: "Monosan Monofaze Elektrik Motorlari, Turkey", // ESI
  5740: "Esyasoft Landis and Gyr, India", // ESL
  5741: "Monosan Monofaze Elektrik Motorlari, Turkey", // ESM
  5742: "Zhejiang Eastron Electronic, China", // ESN
  5743: "Monosan Monofaze Elektrik Motorlari, Turkey", // ESO
  5744: "EFICAA ENSMART SOLUTIONS, India", // ESP
  5746: "Ensor, Switzerland", // ESR
  5747: "Energy Saving Systems, Ukraine", // ESS
  5750: "ESKA VALVE, Turkey", // ESV
  5753: "EasyMeter", // ESY
  5764: "Energy Team, Italy", // ETD
  5771: "ELTEK BROJILA, Croatia", // ETK
  5775: "Sphere of economical technologies, Russian Federation", // ETO
  5776: "Energotechnica", // ETP
  5797: "E E Electronic, Austria", // EUE
  5810: "Eurometers", // EUR
  5811: "Ebeling und Sohn, Germany", // EUS
  5828: "DREWAG NETZ, Germany", // EVD
  5835: "EV KUR ELEKTRIK, Turkey", // EVK
  5836: "Geothermique, United Kingdom", // EVL
  5844: "EVThru, South Korea", // EVT
  5857: "EWATTCH, France", // EWA
  5861: "EWE, Germany", // EWE
  5863: "EWG DOO, Serbia", // EWG
  5875: "ENLESS WIRELESS", // EWS
  5876: "Diehl Metering, Germany", // EWT
  5907: "exceeding solutions, Germany", // EXS
  5908: "LOTRIC Metrology, Slovenia", // EXT
  5925: "Eco eye, United Kingdom", // EYE
  5940: "Enerlyt Potsdam", // EYT
  6179: "Fireangel Safety Technology, United Kingdom", // FAC
  6181: "Fae Technology Company, Brazil", // FAE
  6190: "Fantini Cosmi, Italy", // FAN
  6194: "FARAB, Iran", // FAR
  6195: "FAST, Italy", // FAS
  6308: "Federal Elektrik, Turkey", // FED
  6313: "FUJI ELECTRIC, India", // FEI
  6317: "Fortune Electric, Taiwan", // FEM
  6340: "Fast Forward, Germany", // FFD
  6436: "Fi Muhendislik, Turkey", // FID
  6445: "Frodexim, Bulgaria", // FIM
  6446: "Finder, Germany", // FIN
  6447: "Pietro Fiorentini, Italy", // FIO
  6529: "FLASH ELECTRONICS, India", // FLA
  6532: "Fludia, France", // FLD
  6533: "XIAN FLAG ELECTRONIC, China", // FLE
  6535: "FLOMAG, Czech Republic", // FLG
  6543: "Flonidan, Denmark", // FLO
  6547: "FLASH o s, Turkey", // FLS
  6549: "SHANDONG FEILONG INSTRUMENT, China", // FLU
  6551: "Fluidwell, Netherlands", // FLW
  6552: "FLEXIM Flexible Industriemesstechnik, Germany", // FLX
  6567: "Flow Meter Group, Netherlands", // FMG
  6572: "Siemens Measurements Formerly FML", // FML
  6573: "F IMM, Italy", // FMM
  6596: "findy IoT Solutions, Bulgaria", // FND
  6598: "FlowSystem, Poland", // FNF
  6616: "Flownetix, United Kingdom", // FNX
  6648: "FOXYTECH, Poland", // FOX
  6668: "fifthplay, Belgium", // FPL
  6674: "F Pribor, Belarus", // FPR
  6723: "Shenzhen Friendcom Technology", // FRC
  6725: "Frer, Italy", // FRE
  6741: "OJSC NRPA FRUNZE, Russian Federation", // FRU
  6757: "Flecto Sense, South Africa", // FSE
  6768: "Finmek Space, Italy", // FSP
  6772: "FieldServer Technologies, United States of America", // FST
  6777: "FlowService, Poland", // FSY
  6796: "Tritschler, Germany", // FTL
  6830: "Micro Matic Norge, Norway", // FUN
  6835: "Fuccesso, China", // FUS
  6836: "first utility, United Kingdom", // FUT
  6899: "FW Systeme, Germany", // FWS
  6987: "FUNZIN, South Korea", // FZK
  7220: "GEPDEC SMART TECHNOLOGY, India", // GAT
  7222: "Carlo Gavazzi Controls, Italy", // GAV
  7242: "Grundfoss", // GBJ
  7256: "GRIDBLOX, United States of America", // GBX
  7269: "Genergica, Venezuela", // GCE
  7271: "Goldcard Smart Group, China", // GCG
  7288: "grandcentrix, Germany", // GCX
  7299: "GADICO TECNOLOGIAA", // GDC
  7315: "InnoSense, Switzerland", // GDS
  7331: "GEC Meters", // GEC
  7333: "GE Energy, United Kingdom", // GEE
  7340: "Industrial Technology Research Institute, Taiwan", // GEL
  7342: "Goerlitz", // GEN
  7343: "Green Energy Options, United Kingdom", // GEO
  7344: "GEPDEC INFRATECH", // GEP
  7348: "Genus Electrotech, India", // GET
  7352: "Global Evolution Lighting, Tunisia", // GEX
  7373: "GE Fuji Meter, Japan", // GFM
  7468: "Genus Innovations, India", // GIL
  7470: "Gineers, Bulgaria", // GIN
  7471: "G GIOANOLA, Italy", // GIO
  7521: "G K Assembly, Thailand", // GKA
  7533: "George Kent Bhd, Malaysia", // GKM
  7565: "GETRALINE, France", // GLM
  7567: "NetLand, Poland", // GLO
  7576: "Electrical Equipment Joint Stock Corporation, Vietnam", // GLX
  7587: "GMC I Messtechnik, Germany", // GMC
  7589: "Global Metering Electronics, Netherlands", // GME
  7597: "Gamma International, Egypt", // GMM
  7603: "Gity Madara Sepahan, Iran", // GMS
  7604: "GMT, Germany", // GMT
  7632: "GEPDEC ENERGY, India", // GNP
  7641: "JiangSu GuoNeng Instrument Technology, China", // GNY
  7653: "Genus Power Infrastructures, India", // GOE
  7661: "Zhejiang Gomelong Meter, China", // GOM
  7693: "Polaris Smart Metering, India", // GPM
  7700: "GINTAI POWER TECHNOLOGY, China", // GPT
  7745: "Graesslin, Germany", // GRA
  7748: "Greenradio", // GRD
  7749: "GE2 Green Energy Electronics, Portugal", // GRE
  7753: "Grinpal Energy Management, South Africa", // GRI
  7758: "GREEN ENS, South Korea", // GRN
  7760: "GlobalRnD, Poland", // GRP
  7763: "Garderos, Germany", // GRS
  7765: "G GURU, South Korea", // GRU
  7766: "Gridventure Arge ve Teknoloji Pazarlama A AA, Turkey", // GRV
  7768: "Gurux, Finland", // GRX
  7780: "Genesis Smart Devices, India", // GSD
  7781: "Gridspertise, Italy", // GSE
  7792: "Ingenieurbuero Gasperowicz", // GSP
  7795: "R D Gran System S, Belarus", // GSS
  7796: "Shenzhen Golden Square Technology, China", // GST
  7813: "GREATech, Germany", // GTE
  7821: "G2 misuratori, Italy", // GTM
  7826: "Globaltronics for Electronics E, Egypt", // GTR
  7827: "GIGATRONIK Stuttgart, Germany", // GTS
  7848: "ShenZhen GuangNing Industrial, China", // GUH
  7884: "gAvilar, Netherlands", // GVL
  7910: "Gas u Wassermesserfabrik, Switzerland", // GWF
  7913: "George Wilson Industries Aldermans Green Industrial Estate, United Kingdom", // GWI
  8231: "Hager Electro, Germany", // HAG
  8235: "Hako, Slovakia", // HAK
  8281: "HENAN HUABIAO INSTRUMENT TECHNOLOGY, China", // HBY
  8293: "Hsiang Cheng Electric, China", // HCE
  8301: "Hidroconta U, Spain", // HCM
  8321: "Hidria, Slovenia", // HDA
  8331: "Hydroko, Belgium", // HDK
  8344: "Beijing TianRuiXiangDe Measuring Technology, China", // HDX
  8345: "Dalian hundao instrument, China", // HDY
  8359: "Hamburger Elektronik Gesellschaft", // HEG
  8361: "Hydro Eco Invest, Poland", // HEI
  8363: "Hexing Technology Company, Kenya", // HEK
  8364: "Heliowatt", // HEL
  8365: "Hokkaido Electric Meter Industry, Japan", // HEM
  8370: "Hermes Systems, Australia", // HER
  8375: "Honeywell Integrated Technology, China", // HEW
  8376: "Shenzhen Hexcell Electronics Technology, China", // HEX
  8393: "Nanjing Hu Measurement Control Technology, China", // HFI
  8396: "HFIL Technologies", // HFL
  8402: "SAERI HEAT METERING TECHNOLOGY, China", // HFR
  8429: "HG meter, Denmark", // HGM
  8432: "Hangzhou GreenPalm Technology, China", // HGP
  8453: "HAUSHELD, Germany", // HHE
  8461: "Chongqing Huahong Metering, China", // HHM
  8485: "Shenzhen Holley South Electronics Technology, China", // HIE
  8494: "huebner Informationselektronik, Germany", // HIN
  8500: "ABB, Poland", // HIT
  8525: "Huaihua Jiannan Machinery Factory, China", // HJM
  8555: "Hokuriku Instrumentation, Japan", // HKK
  8564: "Heklatech, Sweden", // HKT
  8580: "Hildebrand Technology, United Kingdom", // HLD
  8596: "Hangzhou Laison Technology, China", // HLT
  8601: "Holley Metering", // HLY
  8617: "HMI Energy, Taiwan", // HMI
  8620: "Holley Technology, China", // HML
  8627: "Hermes Systems, Australia", // HMS
  8628: "Hangzhou Meteronic Technology, China", // HMT
  8629: "Hugo Muller, Germany", // HMU
  8641: "Houshmand Namayeh Afraz, Iran", // HNA
  8644: "Shenzhen Hemei Group, China", // HND
  8654: "Houshmand Namayeh Afraz, Iran", // HNN
  8677: "HOENTZSCH, Germany", // HOE
  8684: "Holosys, Croatia", // HOL
  8686: "Honeywell Technologies, Switzerland", // HON
  8697: "Holley Meters, India", // HOY
  8716: "HPL Socomec, India", // HPL
  8717: "HANGZHOU HPM COMPANY, China", // HPM
  8748: "H Q LAMPS MANUFACTURING, India", // HQL
  8781: "Hefei Runa Metering, China", // HRM
  8787: "HomeRider, France", // HRS
  8794: "HERZ Messtechnik, Germany", // HRZ
  8804: "Ningbo Histar Meter Technology, China", // HSD
  8820: "HST Equipamentos Electronicosa", // HST
  8824: "HST, Germany", // HSX
  8835: "Horstmann Timers and Controls", // HTC
  8837: "Hexing Technologies Europe, Romania", // HTE
  8841: "Shandong Hetong Information Technology, China", // HTI
  8844: "Ernst Heitland Erlenstr, Germany", // HTL
  8851: "HTS Elektronik", // HTS
  8875: "Helbeck Kusemann, Germany", // HUK
  8877: "Humanlitech, Ghana", // HUM
  8903: "Hekatron Vertriebs, Germany", // HVG
  8916: "Helvatron, Switzerland", // HVT
  8931: "Qingdao Hiwits Meter, China", // HWC
  8941: "Beijing Hongwei Chaoda Instrument Manufacturing, China", // HWM
  8948: "Huawei Technologies, China", // HWT
  8964: "Beijing HongHaoXingDa Meters, China", // HXD
  8965: "Hexing Electrical, China", // HXE
  8980: "HEXIN HONGKONG TECHNOLOGY, China", // HXT
  8983: "Hangzhou Xili Watthour Meter Manufacture, China", // HXW
  8995: "Zhejiang Hengye Electronics, China", // HYC
  8996: "Diehl Metering, Germany", // HYD
  8997: "Zhejiang Hyayi Electronic Industry, China", // HYE
  8999: "Diehl Metering, Germany", // HYG
  9005: "Zhejiang Hengye Electronics, China", // HYM
  9011: "Hydrelis", // HYS
  9012: "Zhejiang Hengye Electronics, China", // HYT
  9027: "TANGSHAN HUIZHONG INSTRUMENTATION, China", // HZC
  9033: "TANGSHAN HUIZHONG INSTRUMENTATION, China", // HZI
  9050: "Huizhou Zhongcheng Electronic Technology, China", // HZZ
  9251: "INHEMETER AFRICA COMPANY, Kenya", // IAC
  9285: "IBOT ENERGY SYSTEMS, India", // IBE
  9287: "ITI BANGALORE PLANT, India", // IBG
  9300: "Ikom Bilisim Teknolojileri, Turkey", // IBT
  9314: "Inscobee, South Korea", // ICB
  9317: "Icoal incorporated, United States of America", // ICE
  9323: "I C Technology, South Korea", // ICK
  9325: "Intracom, Greece", // ICM
  9328: "PT Comnets Plus, Indonesia", // ICP
  9331: "ICSA, India", // ICS
  9332: "International Control Metering Technologies, Germany", // ICT
  9333: "i cube, Switzerland", // ICU
  9349: "IMIT", // IDE
  9363: "IDS, Germany", // IDS
  9379: "leonnardo Corporation, Ukraine", // IEC
  9381: "I E Electromatic, Spain", // IEE
  9385: "Informage Energy, India", // IEI
  9390: "Institute of Power Engineering, Poland", // IEN
  9395: "Integrated Electronic Systems Lab, China", // IES
  9411: "infocon, Montenegro", // IFC
  9432: "Infineon Technologies, Germany", // IFX
  9445: "INDKOSQUARE GLOBAL ENGINEERING, India", // IGE
  9453: "ITALGAS RETI, Italy", // IGM
  9458: "iGridS Hebelweg, Germany", // IGR
  9459: "I G S DATAFLOW, Italy", // IGS
  9485: "Shenzhen Inhemeter, China", // IHM
  9508: "PT INDUSTRI TELEKOMUNIKASI Persero, Indonesia", // IID
  9510: "Westenergie Metering, Germany", // IIF
  9541: "ILJIN Electric, South Korea", // IJE
  9547: "IJENKO, France", // IJK
  9573: "IK Elektronik Friedrichsgruener Str, Germany", // IKE
  9581: "Ikom, Croatia", // IKM
  9583: "AE KOM BiliAA im Teknolojileri A AA, Turkey", // IKO
  9587: "IKASIAN, Spain", // IKS
  9635: "madar, Iran", // IMC
  9637: "Fellows, Poland", // IME
  9650: "iMeter, Ukraine", // IMR
  9651: "IMST, Germany", // IMS
  9652: "INTEGRA METERING, Switzerland", // IMT
  9658: "iMezr Innovations, India", // IMZ
  9667: "Incotex, Russian Federation", // INC
  9668: "INDRA SISTEMAS, Spain", // IND
  9669: "INNOTAS Elektronik, Germany", // INE
  9670: "Infometric, Sweden", // INF
  9673: "Altero, Sweden", // INI
  9677: "Inepro Metering, Netherlands", // INM
  9678: "INNEXIV, United States of America", // INN
  9679: "Indotech Switchgear Controls Delhi, India", // INO
  9680: "INNOTAS Produktions, Germany", // INP
  9683: "INSYS MICROELECTRONICS, Germany", // INS
  9684: "Infranet Technologies, Germany", // INT
  9686: "Sensus Metering Systems, Germany", // INV
  9688: "Innolex Engineering, Netherlands", // INX
  9709: "IOmeter, Germany", // IOM
  9710: "Ionics EMS, Philippines", // ION
  9716: "Trilliant Networks, Canada", // IOT
  9732: "IPD Industrial Products, Australia", // IPD
  9775: "Kwhiq, Netherlands", // IQO
  9779: "IQ Systems, South Africa", // IQS
  9797: "IREN Energia, Italy", // IRE
  9825: "Isabellenhutte Heusler, Germany", // ISA
  9829: "INESH SMART ENERGY P, India", // ISE
  9830: "Investcom Szymon Fiedorowicz, Poland", // ISF
  9833: "Akcionarsko Drustvo Insa Industrija Satova, Serbia", // ISI
  9835: "Iskraemeco, Slovenia", // ISK
  9839: "Isoil Industria, Italy", // ISO
  9843: "Iskra, Slovenia", // ISS
  9844: "Ista", // IST
  9847: "iSAtech water, Germany", // ISW
  9857: "iTrona, Switzerland", // ITA
  9858: "Itron Solucoes para Energia e Aguaa, Brazil", // ITB
  9859: "INTECH TUNISIE, Tunisia", // ITC
  9861: "ITRON Electricity, France", // ITE
  9862: "ITF Froeschl, Germany", // ITF
  9863: "ITRON Gas, France", // ITG
  9864: "INTELTEH, Croatia", // ITH
  9865: "ITRON Asia, Indonesia", // ITI
  9867: "Itron, Germany", // ITK
  9868: "Indriya Technologies, India", // ITL
  9869: "Intelligent Metering Systems, Pakistan", // ITM
  9872: "M s ITI, India", // ITP
  9874: "Itron", // ITR
  9875: "ITRON Australasia, Australia", // ITS
  9877: "ITRON United States Itron, United States of America", // ITU
  9879: "ITRON Water, France", // ITW
  9880: "IDEAL TECHNICAL SOLUTIONS, United Arab Emirates", // ITX
  9882: "ITRON, South Africa", // ITZ
  9907: "IUSA DE CV, Mexico", // IUS
  9945: "IVY metering, China", // IVY
  9956: "Inkwell Data, Ireland", // IWD
  9963: "IWK Regler und Kompensatoren", // IWK
  10025: "KAYI ENERGY Hacettepe Universitesi, Turkey", // IYI
  10053: "iZenze, Sweden", // IZE
  10275: "Jay Autocomponents, India", // JAC
  10286: "Janitza electronics, Germany", // JAN
  10310: "Beijing jingyibeifang instrument company", // JBF
  10341: "Janz Contadores de Energia, Portugal", // JCE
  10404: "JED, South Korea", // JED
  10468: "tianjin guangdaweiye measuring instrument technology, China", // JGD
  10470: "Janz Contagem e Gestao de Fluidos, Portugal", // JGF
  10472: "ITSQUARE, South Korea", // JGH
  10497: "Zhejiang JiaHe Instrument, China", // JHA
  10509: "Changzhou Jianhu Intelligentize Meter, China", // JHM
  10574: "BeiJing Fine Clean Enery Technology, China", // JJN
  10615: "QingdaoJakewill Energy Technology, China", // JKW
  10657: "Huizhou JMAO Intelligent Technology, China", // JMA
  10676: "JM TRONIC, Poland", // JMT
  10691: "NINGBO JIANAN ELECTRONICS, China", // JNC
  10692: "J D Electronics, South Korea", // JND
  10698: "JNJ POWERCOM SYSTEMS, India", // JNJ
  10745: "Zhejiang Joy Electronic Technology, China", // JOY
  10765: "JPM INDUSTRIES, India", // JPM
  10861: "Jining Goldwater Science Technology, China", // JSM
  10863: "Schloesser Armaturen, Germany", // JSO
  10868: "JSTech, South Korea", // JST
  10925: "JUMO, Germany", // JUM
  10984: "TIANJIN WANHUA, China", // JWH
  10994: "Shandong jingwei telecommunications equipment, China", // JWR
  10995: "Wesson energy saving technology tianjin, China", // JWS
  11059: "Beijing Jingyuan instrument company, China", // JYS
  11297: "Kamstrup, Denmark", // KAA
  11299: ", Russian Federation", // KAC
  11308: "Kallenbach Elektronik", // KAL
  11309: "Kamstrup Energi", // KAM
  11314: "Keskar Vana Metal Mak Sti, Turkey", // KAR
  11315: "Kamstrup, Denmark", // KAS
  11316: "KATHREIN Werke, Germany", // KAT
  11319: "Kamstrup, Denmark", // KAW
  11336: "K Biesinger, Germany", // KBH
  11339: "KBK ELECTRONICS, Pakistan", // KBK
  11340: "Kimbal, India", // KBL
  11342: "Alpamis IT, Turkey", // KBN
  11406: "KADEN VODOMERY, Czech Republic", // KDN
  11411: "Kedros, Slovakia", // KDS
  11429: "Keewe, Bulgaria", // KEE
  11436: "KELEMINIC, Croatia", // KEL
  11442: "KERMS haftungsbeschraenkt, Germany", // KER
  11443: "Kavosh Electronic Sepahan, Iran", // KES
  11449: "KEYTECH ELEKTRONAE K ANONAE M AA AE RKETAE, Turkey", // KEY
  11469: "Shenzhen Kaifa Technology Chengdu, China", // KFM
  11493: "Guangzhou Keli General Electric, China", // KGE
  11532: "Kohler, Turkey", // KHL
  11559: "Kiwigrid Kleiststrasse, Germany", // KIG
  11572: "KONCAR Instrument transformers, Croatia", // KIT
  11598: "Radniroo Industrial", // KJN
  11621: "KK Electronic", // KKE
  11623: "Katronic, Germany", // KKG
  11653: "SHIJIAZHUANG KELIN ELECTRIC, China", // KLE
  11659: "Kerlink, France", // KLK
  11682: "Kamstrup, Denmark", // KMB
  11700: "Krohne Messtechnik, Germany", // KMT
  11721: "zhangzhou keneng electrical equipment, China", // KNI
  11730: "ISCIENTIFIC TECHSOLUTIONS LABS, India", // KNR
  11736: "KONNEX based users Siemens Regensburg", // KNX
  11780: "Korea Electric Power Industrial Development, South Korea", // KPD
  11788: "KPLC Power, Kenya", // KPL
  11855: "Kromschroder", // KRO
  11860: "Karat, Russian Federation", // KRT
  11885: "Korea Testing Certification, South Korea", // KSM
  11892: "Kundo SystemTechnik", // KST
  11897: "KUNDO SystemTechnik, Germany", // KSY
  11907: "Kerman Tablo, Iran", // KTC
  11916: "Korea Testing Laboratory, South Korea", // KTL
  11947: "KYRGYZ UNAA KURUUSH, Kyrgyzstan", // KUK
  11987: "Klepsan Klape Vana oelcu aletleri San Tic Sti, Turkey", // KVS
  12008: "Zhejiang Songxia Electric Meter, China", // KWH
  12107: "KRIZIK, Czech Republic", // KZK
  12323: "Heinz Lackmann, Germany", // LAC
  12329: "Hangzhou LAISON Technology, China", // LAI
  12334: "Langmatz, Germany", // LAN
  12339: "Lansen Systems, Sweden", // LAS
  12391: "Landis Gyr Meter System Zhuhai, China", // LCG
  12402: "ShanDong LiChuang Science and Technology, China", // LCR
  12421: "Shenzhen Londian Electrics, China", // LDE
  12451: "Lectrotek Systems, India", // LEC
  12457: "PCP International, India", // LEI
  12461: "LEM HEME, United Kingdom", // LEM
  12467: "Lakshmi Electrical Control Systems, India", // LES
  12468: "LAN ENGINEERING TECHNOLOGIES, India", // LET
  12499: "Payolcer Metering Devices, Turkey", // LFS
  12504: "LoggerFlex Smart Devices, Canada", // LFX
  12513: "Landis Gyr", // LGA
  12514: "Landis Gyr, United Kingdom", // LGB
  12515: "Landis Gyr Equipamentos de Medicaoa Brasil, Brazil", // LGC
  12516: "Landis Gyr, Germany", // LGD
  12517: "Landis Gyr, Singapore", // LGE
  12518: "Landis Gyr, Finland", // LGF
  12519: "Ningxia LGG Instrument, China", // LGG
  12521: "Landis Gyr, India", // LGI
  12531: "Landis Gyr, South Africa", // LGS
  12533: "LG Uplus, South Korea", // LGU
  12538: "Landis Gyr, Switzerland", // LGZ
  12545: "Atlantic Meters, South Africa", // LHA
  12590: "Ever Meter, Myanmar", // LIN
  12596: "Punos Electronic, Sweden", // LIT
  12624: "Lars Jansen Productions, Netherlands", // LJP
  12685: "LianYunGang LianLi First Meter, China", // LLM
  12707: "Lumacol, Slovakia", // LMC
  12711: "Luftmeister, Germany", // LMG
  12716: "LUMEL, Poland", // LML
  12720: "LIN MAN POWER TECHNOLOGY, Philippines", // LMP
  12723: "LMS Services, Germany", // LMS
  12739: "Lancier Monitoring, Germany", // LNC
  12747: "Loenk F, South Korea", // LNK
  12756: "Schneider Electric, India", // LNT
  12770: "Lobaro, Germany", // LOB
  12775: "LOGAREX Smart Metering, Czech Republic", // LOG
  12790: "Lovato Electric, Italy", // LOV
  12899: "Lund Science, Sweden", // LSC
  12901: "Landis Staefa electronic", // LSE
  12907: "LS Industrial Systems, South Korea", // LSK
  12912: "Landis Gyr, Germany", // LSP
  12922: "Siemens Building Technologies", // LSZ
  12943: "Labtrino, Sweden", // LTO
  12967: "Landis Gyr, Germany", // LUG
  12974: "LUNA Elektrik Elektronik, Turkey", // LUN
  12976: "LUPUS Electronics, Germany", // LUP
  13044: "Lotus Wireless Technologies, India", // LWT
  13093: "Jiangsu Linyang Electronics, China", // LYE
  13127: "Lackmann Zaehler Gesellschaft mbH, Germany", // LZG
  13347: "RUDNAP Group Meter Control, Serbia", // MAC
  13348: "Maddalena, Italy", // MAD
  13349: "Mates Elektronik Metin Ates, Turkey", // MAE
  13351: "MAGNATECH Smart Grid Solutions, India", // MAG
  13352: "MAHAM ELECTRONIC SAMA SANAT", // MAH
  13358: "Manthey, Germany", // MAN
  13363: "Master Meter Teknoloji, Turkey", // MAS
  13364: "Mitsubishi Electric Automation, Thailand", // MAT
  13368: "MAXMET, South Korea", // MAX
  13384: "MBH POWER, Ghana", // MBH
  13395: "MBS, Germany", // MBS
  13417: "METERING AND COMMUNICATIONS SOLUTIONS, India", // MCI
  13424: "MPSE, Germany", // MCP
  13426: "MICRORISC, Czech Republic", // MCR
  13427: "MetCom Solutions, Germany", // MCS
  13430: "SOCIETE MAROCAINE DES COMPTEURS SMCV, Morocco", // MCV
  13441: "PT MELCOINDA, Indonesia", // MDA
  13445: "Diehl Metering, Germany", // MDE
  13452: "Maddalena, Italy", // MDL
  13460: "Minnotra Energy, India", // MDT
  13464: "mdex, Germany", // MDX
  13475: "Mitsubishi Electric Corporation, Japan", // MEC
  13476: "MAHARASHTRA STATE ELECTRICITY DISTRIBUTION COMPANY, India", // MED
  13477: "Metron Europe, France", // MEE
  13480: "Mueller electronic, Germany", // MEH
  13481: "Sensus Metering Systems, Germany", // MEI
  13484: "Mikroelektronika a d, Bosnia and Herzegovina", // MEL
  13485: "MEMS, Switzerland", // MEM
  13491: "Electrometer U, Spain", // MES
  13492: "METRA Energie Messtechnik, Germany", // MET
  13496: "Metrix Italia, Italy", // MEX
  13588: "Mechatronic Meters, Italy", // MHT
  13603: "Microtronics Engineering, Austria", // MIC
  13604: "MiDo, Italy", // MID
  13609: "Apator Miitors ApS, Denmark", // MII
  13610: "MAXWELL, India", // MIJ
  13611: "Mikroklima, Czech Republic", // MIK
  13612: "Milur Smart System liability company, Russian Federation", // MIL
  13613: "n Intelligence Meters Sdn Bhd, Malaysia", // MIM
  13615: "Metiundo, Germany", // MIO
  13618: "MIR Research and Production Association, Russian Federation", // MIR
  13619: "Iskra MIS, Slovenia", // MIS
  13620: "Sagemcom Energy Telecom, France", // MIT
  13622: "MIVO Technology, Sweden", // MIV
  13665: "mirakonta, Germany", // MKA
  13669: "MKEK Genel Mudurlugu Gazi Fisek ELSA, Turkey", // MKE
  13676: "MAKEL Elektrik Malzemeleri, Turkey", // MKL
  13683: "MAK SAY Elektrik Elektronik, Turkey", // MKS
  13713: "MeterLinq, Italy", // MLQ
  13714: "PKK Milandr, Russian Federation", // MLR
  13731: "Modern Meters, Syria", // MMC
  13734: "MEMF Electrical Industries, Saudi Arabia", // MMF
  13737: "MyMeterInfo, France", // MMI
  13741: "MATRICA", // MMM
  13744: "MATRIXMETERS, India", // MMP
  13747: "Brunswick Bowling and Billiards UK, United Kingdom", // MMS
  13748: "METMOTEC, United Kingdom", // MMT
  13779: "MANAS Elektronik, Turkey", // MNS
  13783: "MENOWATT GE, Italy", // MNW
  13802: "Mojec International, Nigeria", // MOJ
  13811: "MOMAS SYSTEMS, Nigeria", // MOS
  13812: "The Motwane Manufacturing Company, India", // MOT
  13825: "Mega Power Automation International, Hong Kong", // MPA
  13836: "Metrona Polska Pomiary i Rozliczenia, Poland", // MPL
  13842: "Michael Rac, Germany", // MPR
  13843: "Multiprocessor Systems, Bulgaria", // MPS
  13902: "LLC RPC MEtRON, Ukraine", // MRN
  13908: "MIRTEK, Russian Federation", // MRT
  13922: "MISA SDN BHD, Malaysia", // MSB
  13925: "Mahashakti Energy, India", // MSE
  13929: "MIC ELECTRONICS, India", // MSI
  13933: "MS M, South Korea", // MSM
  13935: "Metiso, Serbia", // MSO
  13940: "Microsoft Corporation, Taiwan", // MST
  13945: "MAK SAY Elektrik Elektronik Malzemeleri, Turkey", // MSY
  13955: "Metering Technology Corporation", // MTC
  13956: "Removed November, United States of America", // MTD
  13957: "The ian German for Water Meter Manufacturing Metrotec, Egypt", // MTE
  13960: "njmeter, China", // MTH
  13961: "Microtech Industries, Pakistan", // MTI
  13964: "Advance Metering technology, India", // MTL
  13965: "Metrum, Sweden", // MTM
  13966: "Merytronic, Spain", // MTN
  13968: "Modern Transformers, India", // MTP
  13970: "METER, Russian Federation", // MTR
  13971: "MeteRSit, Italy", // MTS
  13972: "PT Metalindo Teratai Putra, Indonesia", // MTT
  13976: "Matrix Energy, India", // MTX
  13995: "Meters UK Whitegate White Lund Trading Estate, United Kingdom", // MUK
  14057: "Magic Wand Intelligent Systems, India", // MWI
  14069: "METRONA Union, Germany", // MWU
  14085: "Hangzhou MingX technology, China", // MXE
  14093: "Maxim Integrated Circuit Design, India", // MXM
  14131: "MODEMSYS, Spain", // MYS
  14373: "Nanjing NengRui Automation Equipment, China", // NAE
  14375: "Networked Energy Services, Switzerland", // NAG
  14386: "NARI Group Corporation NARI Technology Development, China", // NAR
  14387: "NAS Instruments OU", // NAS
  14388: "Natural Heat Ahorro Energetico, Spain", // NAT
  14443: "NC Korea, South Korea", // NCK
  14470: "NUCLEO DURO FELGUERA, Spain", // NDF
  14477: "Northern Design, United Kingdom", // NDM
  14501: "Northern Electric Equipment Joint Stock Company, Vietnam", // NEE
  14505: "NEWLECTRIC INNOVATION, India", // NEI
  14511: "NeoVac, Switzerland", // NEO
  14514: "Nero Electronics, Belarus", // NER
  14515: "NORA ELK MALZ SAN ve TIC, Turkey", // NES
  14516: "Netatmo, France", // NET
  14520: "Nexelec, France", // NEX
  14576: "Ngenic, Poland", // NGP
  14635: "NIK ELEKTRONIKA, Ukraine", // NIK
  14643: "Nisko Industries, Israel", // NIS
  14659: "NAMJUN, South Korea", // NJC
  14707: "N ERGIE Kundenservice, Germany", // NKS
  14729: "Next Level Integration, Germany", // NLI
  14757: "SI ART, Russian Federation", // NME
  14759: "NMG, Poland", // NMG
  14771: "Nisko Advanced Metering Solutions, Israel", // NMS
  14772: "Nova met, Czech Republic", // NMT
  14804: "2N Telekomunikace, Czech Republic", // NNT
  14825: "NOITAC sp k, Poland", // NOI
  14833: "NorthQ, Denmark", // NOQ
  14838: "NovaTech, United States of America", // NOV
  14860: "CSIR National Physical Laboratory, India", // NPL
  14867: "NEOPIS, South Korea", // NPS
  14868: "CJSC PROGTECH, Russian Federation", // NPT
  14925: "Norm Elektronik, Turkey", // NRM
  14926: "Neuron, Switzerland", // NRN
  14932: "Zavod Nartis, Russian Federation", // NRT
  14949: "North Smart Equipment, China", // NSE
  14960: "M S N S Power, India", // NSP
  14979: "Nuri Telecom, South Korea", // NTC
  14989: "Netinium, Netherlands", // NTM
  15044: "METER", // NVD
  15054: "NOVEN ENERGY AND ICT, Turkey", // NVN
  15079: "NINGBO WASSER GERAETE, China", // NWG
  15085: "Ningbo Water Meter, China", // NWM
  15111: "nexgen consultancy, India", // NXG
  15120: "NXP Semiconductors, Netherlands", // NXP
  15143: "Ningbo Yonggang Instrument, China", // NYG
  15150: "Nanjing Yuneng Instrument, China", // NYN
  15186: "Nordwestdeutsche Zaehlerrevision Ing Aug Knemeyer, Germany", // NZR
  15411: "Omni Agate Systems, India", // OAS
  15427: "shandong oubiao information Technology, China", // OBC
  15429: "Obeo, Norway", // OBE
  15442: "RMZ OBRIY, Ukraine", // OBR
  15497: "OAS Digital Infrastructures, India", // ODI
  15499: "Okinawa Denki Kogyo, Japan", // ODK
  15525: "ONUR Elektrik ve Elektronik, Turkey", // OEE
  15681: "ELECTRICAL CIRCUIT BREAKER FACTORY FOR INDUSTRY ECB, Saudi Arabia", // OJA
  15726: "be storaged, Germany", // OKN
  15753: "Olivetti, Italy", // OLI
  15783: "Open Metering System Group OMS Group e V", // OMG
  15795: "OMNISYSTEM, South Korea", // OMS
  15813: "Omnicore Stratejik Teknolojiler Sti, Turkey", // ONE
  15826: "ONUR Elektroteknik, Turkey", // ONR
  15827: "ONUR Elektroteknik, Turkey", // ONS
  15892: "Optec, Switzerland", // OPT
  15938: "ORBIS Tecnologia Electrica, Spain", // ORB
  15949: "Ormazabal, Spain", // ORM
  15969: "Osaki Electric Europe, Japan", // OSA
  15970: "Ocea Smart Building, France", // OSB
  15971: "Oriental Sales Corporation, India", // OSC
  15979: "Osaki Electric, Japan", // OSK
  15990: "Onstar Venture, India", // OSV
  16013: "OTMetric, France", // OTM
  16019: "Shenzhen Oasis Technology Service, China", // OTS
  16171: "GULLWING TIANJIN INDUSTRY DEVELOPMENGT, China", // OYK
  16203: "Oz kar Enerji, Turkey", // OZK
  16420: "PadMess, Germany", // PAD
  16422: "FAP PAFAL, Poland", // PAF
  16425: "PAIBOONKIJTHANA, Thailand", // PAI
  16427: "Paktim Energy Sp zo o, Poland", // PAK
  16430: "Panasonic Corporation, Japan", // PAN
  16466: "PFIFFNER do Brasil, Brazil", // PBR
  16485: "Precise Electronics, Thailand", // PCE
  16489: "POLYCAB, India", // PCI
  16498: "Powercom, Israel", // PCR
  16517: "Pfiffner Deutschland, Germany", // PDE
  16536: "Paradox Engineering, Switzerland", // PDX
  16545: "PEA J V Company, Ecuador", // PEA
  16549: "Prantech Energy Solutions, India", // PEE
  16556: "Pak Elektron PEL, Pakistan", // PEL
  16557: "peerMetering, Germany", // PEM
  16560: "POWRTEC ENERGY, India", // PEP
  16562: "Perry Electric, Italy", // PER
  16585: "PFIFFNER Instrument Transformers, Switzerland", // PFI
  16613: "PayGo Energy", // PGE
  16624: "P G P Smart Sensing, Belgium", // PGP
  16652: "HangZhou PAX Electronic Technology, China", // PHL
  16664: "Phoenix Systems, Poland", // PHX
  16681: "PiiGAB Processinformation i Goteborg, Sweden", // PII
  16683: "pikkerton, Germany", // PIK
  16684: "Pilot Systems London, United Kingdom", // PIL
  16685: "Power Innovation, Germany", // PIM
  16686: "PFIFFNER Instr Transformers, India", // PIN
  16688: "Hermann Pipersberg jr, Germany", // PIP
  16694: "Pivot Access, Rwanda", // PIV
  16780: "POLL, Czech Republic", // PLL
  16782: "Prolan Process Control Company, Hungary", // PLN
  16783: "Weihai Ploumeter, China", // PLO
  16789: "Plutus Smart Energy Solutions, India", // PLU
  16805: "Pal Mohan Electronics, India", // PME
  16807: "Sensus Metering Systems, Germany", // PMG
  16812: "PROGRESSIVE METERS, India", // PML
  16816: "REDUR, Germany", // PMP
  16819: "PMS Elektronik, Germany", // PMS
  16824: "Dell Anna Ing Luca, Italy", // PMX
  16835: "PNC Technology, South Korea", // PNC
  16839: "PAKTIM METERING, Nigeria", // PNG
  16868: "PowerOneData, India", // POD
  16876: "Pronal sp k, Poland", // POL
  16887: "PowerApp, Denmark", // POW
  16890: "ZEUP Pozyton, Poland", // POZ
  16899: "Power Plus Communications, Germany", // PPC
  16908: "Prompribor plant, Russian Federation", // PPL
  16915: "Palace Power Systems, South Africa", // PPS
  16944: "PQ Plus, Germany", // PQP
  16961: "Paya Ravesh Aria", // PRA
  16965: "Predicate Software, South Africa", // PRE
  16967: "Paud Raad Industrial Group, Iran", // PRG
  16969: "Polymeters Response International", // PRI
  16973: "Promatic, Croatia", // PRM
  16975: "Proton Elektromed, Turkey", // PRO
  16985: "ShanDong LiChuang Science and Technology, China", // PRY
  16995: "PS Tec, Korea,  Democratic People's Republic of (North Korea)", // PSC
  16997: "pSenso, Poland", // PSE
  17006: "PySENSE, Poland", // PSN
  17011: "Part Sanat Sanjesh, Iran", // PSS
  17012: "PS Tec, South Korea", // PST
  17033: "Prolific Technology, Taiwan", // PTI
  17042: "Pfiffner Transformatoer, Turkey", // PTR
  17067: "Paktim Consulting UK, United Kingdom", // PUK
  17068: "NPP Teplovodokhran", // PUL
  17108: "Pavo Tasarim Uretim Elektronik Tic, Turkey", // PVT
  17122: "Paul Wegener, Germany", // PWB
  17138: "Powrtec, United States of America", // PWR
  17155: "Phoenix Contact, Germany", // PXC
  17205: "PYUNGIL, South Korea", // PYU
  17208: "Pyrexx, Germany", // PYX
  17554: "Quadrar Tecnologia, Brazil", // QDR
  17555: "Qundis, Germany", // QDS
  17616: "QFP Engineering, Italy", // QFP
  17797: "Quickline Energy, Switzerland", // QLE
  18020: "Quicksand, Belgium", // QSD
  18067: "QT systems, Sweden", // QTS
  18467: "Michael Rac, Germany", // RAC
  18468: "Radiocrafts, Norway", // RAD
  18477: "Rossweiner Armaturen und Messgeraete OHG, Germany", // RAM
  18483: "Rubikon Apskaitos Sistemos, Lithuania", // RAS
  18489: "Rayleigh Instruments, United Kingdom", // RAY
  18509: "R B M, Italy", // RBM
  18533: "RC ENERGY METERING, India", // RCE
  18571: "Wuhan Radarking Electronics, China", // RDK
  18573: "RDMx Consulting, Brazil", // RDM
  18595: "Zhejiang Reallin Electron, China", // REC
  18598: "REFERANS ELEKTRIK SAYACLARI, Turkey", // REF
  18601: "RENESAS ELECTRONICS, India", // REI
  18604: "Relay, Germany", // REL
  18605: "Remote Energy Monitoring, United Kingdom", // REM
  18608: "Radiant Energy Solutions, India", // REP
  18611: "Renesas Electronics, Singapore", // RES
  18702: "Rhino, Poland", // RHN
  18723: "Richa Equipments, India", // RIC
  18732: "Rikken Instrumentation, India", // RIL
  18733: "CJSC Radio and Microelectronics, Russian Federation", // RIM
  18734: "Rayleigh Instruments, United Kingdom", // RIN
  18740: "Ritz Instrument Transformers, Germany", // RIT
  18744: "Raonix, South Korea", // RIX
  18746: "RIZ Transmitters, Croatia", // RIZ
  18788: "Ramakrishna Electro Components, India", // RKD
  18789: "Viterra Energy Services formerly Raab Karcher ES", // RKE
  18849: "Mess und Regeltechnik, Germany", // RMA
  18855: "RMG Messtechnik, Germany", // RMG
  18857: "Racemosa Energy, India", // RMI
  18860: "ROLEX METERS RPIVATE, India", // RML
  18866: "Advanced Technology RAMAR, United Kingdom", // RMR
  18868: "Richter Messtechnik, Germany", // RMT
  18903: "Renergy Micro Technologies, China", // RNW
  18923: "ROKIP Liability Company, Russian Federation", // ROK
  19041: "Rahrovan Sepehr Andisheh", // RSA
  19053: "Zhejiang Risesun Science and Technology, China", // RSM
  19063: "RSW Technik, Germany", // RSW
  19489: "Sanjesh Afzar Asia, Iran", // SAA
  19491: "SACOFGAS, Italy", // SAC
  19493: "SAE IT systems, Germany", // SAE
  19495: "Sagemcom Energy Telecom, France", // SAG
  19500: "Salzer Electronics, India", // SAL
  19501: "Siemens OEsterreich AMIS Automated Metering and Information System, Austria", // SAM
  19502: "SANN Stockholm, Sweden", // SAN
  19504: "Diehl Metering, Germany", // SAP
  19508: "SATEC, Israel", // SAT
  19523: "Saia Burgess Controls, Switzerland", // SBC
  19553: "SENECA, Italy", // SCA
  19557: "Seo Chang Electric Communication, South Korea", // SCE
  19560: "Schinzel", // SCH
  19564: "Steama Company", // SCL
  19565: "CalinMeter, China", // SCM
  19570: "Sanchuan Wisdom Technology, China", // SCR
  19572: "S I C E Telecomunicazioni, Italy", // SCT
  19575: "ScatterWeb, Germany", // SCW
  19587: "SdC Sistemas de Contagem", // SDC
  19597: "Shandong Delu Measurement, China", // SDM
  19603: "Sitec Elettronica industriale, Italy", // SDS
  19619: "Schneider Electric, Canada", // SEC
  19621: "El Sewedy Electrometer, Egypt", // SEE
  19624: "SAMRAKSHANA ELECTRICALS, India", // SEH
  19625: "Sicom Electronics International, Chile", // SEI
  19627: "StroyEnergoKom, Russian Federation", // SEK
  19628: "Selec Controls, India", // SEL
  19629: "Smart Meter Company, Myanmar", // SEM
  19630: "Sensus Metering Systems, Germany", // SEN
  19631: "SENSOCO Greatech, Germany", // SEO
  19636: "Sagemcom Energy Telecom, France", // SET
  19653: "WUHAN SANFRAN ELECTRONICS, China", // SFE
  19657: "Siemens DI PA MI, Germany", // SFI
  19666: "WUHAN SANFRAN ELECTRONICS, China", // SFR
  19668: "Sotflink, Czech Republic", // SFT
  19681: "smartGAS Mikrosensorik, Germany", // SGA
  19689: "Smartgrid Innovations, India", // SGI
  19693: "Swiss Gas Metering, Switzerland", // SGM
  19694: "SYGNITY, Poland", // SGN
  19704: "Gao Xiang Water Meter, China", // SGX
  19716: "Beijing SanHuaDeBao Energy Technoligy, China", // SHD
  19717: "Shenzhen SingHang Elec tech, China", // SHE
  19725: "Shanghai Metering, China", // SHM
  19732: "Shitek Technology, Italy", // SHT
  19747: "SICK Engineering, Germany", // SIC
  19749: "Siemens", // SIE
  19751: "Sigrenea, France", // SIG
  19754: "SUN STAR INDUSTRIES, India", // SIJ
  19756: "Silicon Laboratories, United States of America", // SIL
  19757: "Sana Intelligent Meter, Iran", // SIM
  19758: "SINAPSI, Italy", // SIN
  19763: "Sevme Informatique Service, France", // SIS
  19764: "SITEL, Serbia", // SIT
  19766: "Sieverding Heizungs und Sanitaertechnik, Germany", // SIV
  19768: "Six Innovation, Sweden", // SIX
  19777: "Sheng Jay Automation Technologies, Taiwan", // SJA
  19817: "S K I, Germany", // SKI
  19819: "Shikoku Instrumentation, Japan", // SKK
  19822: "BENTEX CONTROL AND SWITCH GEAR, India", // SKN
  19825: "SKI sherkate kontorsazi, Iran", // SKQ
  19828: "SkyToll, Slovakia", // SKT
  19833: "SKYLARK SMARTMETERS, India", // SKY
  19842: "Schlumberger Industries, France", // SLB
  19847: "Silergy Technologies", // SLG
  19856: "Sylop spolka z ograniczona odpowiedzialnoscia sp k, Poland", // SLP
  19862: "Solvimus, Germany", // SLV
  19863: "SOLID WAY SAS, France", // SLW
  19864: "Ymatron, Switzerland", // SLX
  19873: "Smart me, Switzerland", // SMA
  19875: "Sierra Monitor Corporation, United States of America", // SMC
  19877: "Siame, Tunisia", // SME
  19878: "Star Measure, Brazil", // SMF
  19879: "Samgas, Italy", // SMG
  19881: "PT SMART METER, Indonesia", // SMI
  19884: "Siemens Measurements", // SML
  19885: "Smart Metering, Italy", // SMM
  19886: "Saiman Corporation, Kazakhstan", // SMN
  19888: "LLC FIRM SEMPAL, Ukraine", // SMP
  19889: "SMARTMETERQ, Italy", // SMQ
  19890: "Saudi Meters Company, Saudi Arabia", // SMR
  19891: "Smart Metering Solutions Changsha, China", // SMS
  19892: "Smarteh, Slovenia", // SMT
  19894: "Societe Marocaine des Compteurs, Morocco", // SMV
  19896: "Smart Meters Technologies Sdn Bhd, Malaysia", // SMX
  19906: "Stromnetz Berlin, Germany", // SNB
  19917: "ShenZhen Northmeter, China", // SNM
  19922: "NTN SNR, France", // SNR
  19923: "Signals and Systems, India", // SNS
  19924: "SensorNet, Italy", // SNT
  19939: "SOCOMEC, France", // SOC
  19942: "Softflow de, Germany", // SOF
  19943: "Sogecam Industrial, Spain", // SOG
  19948: "Soledia, Italy", // SOL
  19949: "Somesca, France", // SOM
  19950: "Sontex, Switzerland", // SON
  19955: "SOFTSERVICE, Ukraine", // SOS
  19956: "Sotronix, Germany", // SOT
  19971: "JSC RPC Spektr, Russian Federation", // SPC
  19973: "SUKHILA POWER ELECTRONICS, India", // SPE
  19980: "Diehl Metering, Germany", // SPL
  19981: "Stelmec Powercom, India", // SPM
  19992: "Sensus Metering Systems, Germany", // SPX
  19994: "SPowerZ Solutions, India", // SPZ
  20037: "Guangzhou Sunrise Electronics Development, China", // SRE
  20038: "Saraf Industries, India", // SRF
  20046: "Shandong SARON Intelligent Technology, China", // SRN
  20054: "Servic, Ukraine", // SRV
  20069: "S T Smart Energy, Austria", // SSE
  20071: "Super Star Electronics, Bangladesh", // SSG
  20073: "Security Solutions Institute, Bulgaria", // SSI
  20076: "Synapsys Solutions", // SSL
  20077: "SCC METERS, Bangladesh", // SSM
  20078: "Silver Spring Networks, United States of America", // SSN
  20083: "SUEZ SMART SOLUTIONS, France", // SSS
  20084: "Qingdao Haina Electric Automation Systems, China", // SST
  20097: "Shenzhen Star Instrument, China", // STA
  20099: "Sunrise Technology, China", // STC
  20100: "Stedin, Netherlands", // STD
  20101: "Satera Elektrik Elektronik San ve Tic", // STE
  20102: "STACKFORCE, Germany", // STF
  20108: "Saudi Technical Group, Saudi Arabia", // STL
  20109: "STELMEC, India", // STM
  20110: "Hunan Stron Smart, China", // STN
  20111: "ABB STOTZ KONTAKT, Germany", // STO
  20112: "Spectrum Tool Engineers, India", // STP
  20114: "Strike Technologies, South Africa", // STR
  20115: "Swistec Systems, Switzerland", // STS
  20118: "STV Automation Branch of STV Electronic, Germany", // STV
  20119: "Siterwell Electronics, China", // STW
  20122: "Steinbeis Innovation Center Embedded Design and Networking, Germany", // STZ
  20140: "SINHAL UDYOG, India", // SUL
  20141: "Sumeru Verrdhe Technologies, India", // SUM
  20142: "TIAN JIN SUN ENERGY TECHNOLOGY, China", // SUN
  20144: "SUPERMAX COMPONENTS, India", // SUP
  20152: "Supermax Components, India", // SUX
  20173: "AB Svensk Vaermemaetning SVM", // SVM
  20180: "SPUTNIK, Russian Federation", // SVT
  20201: "Swistec, Germany", // SWI
  20205: "Smart Water Metering, Canada", // SWM
  20211: "Stadtwerke Senftenberg, Germany", // SWS
  20212: "Beijing Swirling Technology, China", // SWT
  20259: "Sycous Leeds Innovation Centre, United Kingdom", // SYC
  20260: "Sydler Electronics, India", // SYD
  20270: "SMSISTEM, Turkey", // SYN
  20274: "SAYRON GLOBAL ENERJAE A AA, Turkey", // SYR
  20275: "Softwareentwicklung Systemdesign, Austria", // SYS
  20280: "SyxthSense, United Kingdom", // SYX
  20307: "Szerver Szektor Kft, Hungary", // SZS
  20519: "Telma, Switzerland", // TAG
  20524: "TALAMONA, Italy", // TAL
  20526: "Tianxin instrument group, China", // TAN
  20531: "Pouyeshgaran Tabriz Azma, Iran", // TAS
  20532: "Tatung, Taiwan", // TAT
  20533: "TARGUS TECHNOLOGIES, India", // TAU
  20537: "Taytech Otomasyon ve Bilisim Teknolojileri Sti, Turkey", // TAY
  20538: "PoyeshGaran Sahandzaran Tabrizazma, Iran", // TAZ
  20558: "TBEA Nanjing Intelligent Electric, China", // TBN
  20563: "TEBAS END ISI SIS INS TUR SAN VE TIC STI, Turkey", // TBS
  20581: "Qingdao iTechene Technologies, China", // TCE
  20584: "Techem", // TCH
  20589: "TCOM, Serbia", // TCM
  20591: "Teco, Czech Republic", // TCO
  20592: "Telecard Prilad, Ukraine", // TCP
  20596: "Tecnotel, Italy", // TCT
  20600: "Qingdao Topscomm Communication, China", // TCX
  20602: "Tianjin Chuangzhan Tongcheng Technology Development, China", // TCZ
  20611: "Telecom Design, France", // TDC
  20641: "TEAM R", // TEA
  20643: "TECSON Digital, Germany", // TEC
  20648: "IOTech", // TEH
  20649: "Tohoku Electric Meter Industry, Japan", // TEI
  20651: "Tekmar Regelsysteme, Germany", // TEK
  20652: "TURBO ENERGY, Nigeria", // TEL
  20654: "TekhnoEnergo, Russian Federation", // TEN
  20655: "ubitricity Gesellschaft fur verteilte Energiesysteme mbH, Germany", // TEO
  20656: "TEPEECAL, France", // TEP
  20658: "Tavrida Electric Russia, Russian Federation", // TER
  20661: "TOSHELECTROAPPARAT FE, Uzbekistan", // TEU
  20675: "Toos Fuse, Iran", // TFC
  20679: "TERMICS Divisione FIMIGAS, Italy", // TFG
  20728: "Tiesse, Italy", // TGX
  20741: "Theben, Germany", // THE
  20755: "JOZI 20, Bulgaria", // THS
  20759: "TW TEAMWARE, Italy", // THW
  20771: "TOKYO KEISO, Japan", // TIC
  20772: "TIDE, South Korea", // TID
  20775: "ZHONGHUAN TIG, China", // TIG
  20777: "TRIKALA INDUSTRIES, India", // TII
  20780: "Thermal Integration, United Kingdom", // TIL
  20784: "TIP, Germany", // TIP
  20787: "Texas Instruments, Hong Kong", // TIS
  20792: "Tixi Com", // TIX
  20846: "TECHKNAVE, India", // TKN
  20851: "Teksan Teknolojik OElcum Sistemleri, Turkey", // TKS
  20867: "TELECON GALICIA, Spain", // TLC
  20877: "Theodor Lange Messgeraete, Germany", // TLM
  20882: "Telereading, Italy", // TLR
  20883: "TLS Energimaetning, Sweden", // TLS
  20884: "Telecommunication Technologies, Ukraine", // TLT
  20889: "LLC SPE Telemetry, Ukraine", // TLY
  20901: "TECHNO METERS ELECTRONICS, India", // TME
  20907: "Timi Kosova Sh p k", // TMK
  20915: "TEMASS IMALAT, Turkey", // TMS
  20922: "TMZ Thuringer Mess und Zaehlerwesen Service, Germany", // TMZ
  20948: "Deltamess DWWF, Germany", // TNT
  20965: "Top For Electrical Industries, Egypt", // TOE
  20976: "KMB systems, Czech Republic", // TOP
  20994: "2 Plus AD, Bulgaria", // TPB
  20995: "Taipit measuring equipment, Russian Federation", // TPC
  20999: "Texnopark, Uzbekistan", // TPG
  21001: "Transfopower Industries, Pakistan", // TPI
  21002: "TAKAHATA PRECISION, Japan", // TPJ
  21004: "Teplocom Holding, Russian Federation", // TPL
  21018: "PLC Technology", // TPZ
  21059: "Traco Doo, Serbia", // TRC
  21063: "Trench, Germany", // TRG
  21065: "Tritech Technology, Sweden", // TRI
  21066: "SHENZHEN TECHRISE ELECTRONICS, China", // TRJ
  21068: "Trilliant, Canada", // TRL
  21070: "TERRANOVA, Italy", // TRN
  21071: "TROX, Germany", // TRO
  21077: "Truteq Wireless, South Africa", // TRU
  21078: "Transvaro Elektron Aletleri, Turkey", // TRV
  21079: "Triowatt", // TRW
  21080: "Beijing TianRuiXiang Equipment, China", // TRX
  21082: "TR Group, South Africa", // TRZ
  21092: "Theobroma Systems Design und Consulting, Austria", // TSD
  21093: "Nichi Manufacturing, India", // TSE
  21095: "Testo Sensor, Germany", // TSG
  21111: "T7 WENMAX SDN BHD, Malaysia", // TSW
  21127: "Tatung, Taiwan", // TTG
  21133: "Toshiba Toko Meter Systems, Japan", // TTM
  21134: "Tatung, Taiwan", // TTN
  21138: "Tetraedre, Switzerland", // TTR
  21140: "Telephone and Telegraph Technique, Bulgaria", // TTT
  21170: "TURKSAY ELEKTRONIK ELEKTRIK ENDUSTRISI", // TUR
  21231: "2Flow, Sweden", // TWO
  21260: "CETC46 TianJin New Top Electronics Technology, China", // TXL
  21543: "Uher", // UAG
  21577: "Ubitronix system solutions, Austria", // UBI
  21593: "ubitricity Gesellschaft fur verteilte Energiesysteme mbH, Germany", // UBY
  21673: "United Electrical Industries, India", // UEI
  21676: "united electrical industries, India", // UEL
  21737: "United Gas Industries", // UGI
  21748: "DP UKRGAZTECH Ukrainian gas technologies, Ukraine", // UGT
  21773: "Micronics, United Kingdom", // UHM
  21961: "Univations, Hong Kong", // UNI
  21965: "UniMetric, Croatia", // UNM
  22035: "UMA POLY SOLUTIONS, India", // UPS
  22093: "Urmet Telecomunicazioni, Italy", // URM
  22115: "Usanca Soluciones, Spain", // USC
  22150: "UtiliFlex, United States of America", // UTF
  22153: "Utilia, Italy", // UTI
  22156: "United Telecoms, India", // UTL
  22163: "UNIQUE TECHNOSOLUTIONS, India", // UTS
  22164: "UtiliTools, Germany", // UTT
  22569: "Shete Advanced Technologies, India", // VAI
  22572: "Valkoder, Bulgaria", // VAL
  22578: "VARAAHI ELECTROMECH, India", // VAR
  22672: "Plant Vodopribor management company, Russian Federation", // VDP
  22691: "Energo Control, Ukraine", // VEC
  22700: "VELANKANI ELECTRONICS, India", // VEL
  22702: "INVENDIS TECHNOLOGIES, India", // VEN
  22706: "VERAUT, Austria", // VER
  22707: "Viterra Energy Services", // VES
  22712: "Vertex Electronics, Pakistan", // VEX
  22739: "Semas, Serbia", // VFS
  22767: "Vango Technologies, Taiwan", // VGO
  22821: "Vientech, France", // VIE
  22827: "VI KO ELEKTRIK, Turkey", // VIK
  22829: "VIEN ENERJI SISTEMLERI SANAYI VE TICARET SIRKETI, Turkey", // VIM
  22830: "Vektor innovations, India", // VIN
  22832: "VIPA CZ, Czech Republic", // VIP
  22836: "Vitir, Norway", // VIT
  22932: "ABB EPMV Division, Czech Republic", // VLT
  22960: "VAMP, Finland", // VMP
  22981: "Vision Networks, India", // VNE
  23049: "Van Putten Instruments", // VPI
  23052: "Verticross, India", // VPL
  23141: "Valenciana Smart Energy of Mediterranean Sea, Spain", // VSE
  23150: "Viewshine, China", // VSN
  23171: "Vitelec, Netherlands", // VTC
  23175: "vemm tec Messtechnik", // VTG
  23179: "Linkwell Telesystems, India", // VTK
  23182: "VITEX NOVA, Ukraine", // VTN
  23194: "VitzroSys, South Korea", // VTZ
  23254: "VIVAVIS, Germany", // VVV
  23588: "Waher Data, Sweden", // WAD
  23592: "WAHESOFT, Germany", // WAH
  23593: "Chongqing WECAN Precision Instruments, China", // WAI
  23596: "Wallaby Metering Systems, India", // WAL
  23694: "Webdyn, France", // WDN
  23714: "Webolution, Germany", // WEB
  23719: "WEG Equipamentos Eletricos Automacao, Brazil", // WEG
  23720: "E Wehrle, Germany", // WEH
  23724: "WELLTECH automation, China", // WEL
  23728: "Weptech elektronik, Germany", // WEP
  23764: "Waft Embedded Circuit Solutions, India", // WFT
  23790: "Wasser Geraete, Germany", // WGN
  23792: "GreenPoint, Poland", // WGP
  23829: "Wasion Kft, Hungary", // WHU
  23847: "Wigersma Sikkema, Netherlands", // WIG
  23851: "WIKON Kommunikationstechnik, Germany", // WIK
  23854: "Windmill Innovations, Netherlands", // WIN
  23916: "Shenyang jia DE lian yi energy technology, China", // WKL
  23928: "JINING WUKEXING METER, China", // WKX
  23983: "Westermo Teleindustri, Sweden", // WMO
  24003: "wireless netcontrol, Germany", // WNC
  24023: "Wistron NeWeb Corporation Marketing Center, Taiwan", // WNW
  24055: "Sciknow Techno Solutions, India", // WOW
  24090: "Weepiez SaS, France", // WPZ
  24164: "Yantai Wisdom Electric, China", // WSD
  24165: "Wasion Group, China", // WSE
  24167: "ZHEJIANG WELLSUN INTELLIGENT TECHNOLOGY, China", // WSG
  24173: "winAMR Systems, India", // WSM
  24178: "WESER, Russian Federation", // WSR
  24201: "Weihai Sunts Electric Meter, China", // WTI
  24204: "Wipro Technologies, India", // WTL
  24205: "Watertech, Italy", // WTM
  24212: "Watertech, Italy", // WTT
  24242: "Wurm Elektronische Systeme, Germany", // WUR
  24391: "Neumann Wasserzaehler Glaubitz, Germany", // WZG
  24404: "Wizit, South Korea", // WZT
  24623: "Info Solution, Italy", // XAO
  24741: "XEE Technology, Germany", // XEE
  24749: "XEMTEC, Switzerland", // XEM
  24879: "XIOTA, India", // XIO
  24909: "XJ Metering, China", // XJM
  24967: "X LOGIC, Croatia", // XLG
  24993: "XMASTER, Poland", // XMA
  25016: "Xemex, Belgium", // XMX
  25104: "XYROSYS, India", // XPP
  25229: "Suntront Tech, China", // XTM
  25234: "HENAN SUNTRONT TECH, China", // XTR
  25241: "LianYuanGang Tengyue Electronics Technology", // XTY
  25388: "Sensus Ludwigshafen, Germany", // XYL
  25732: "Jilin Yongda Group", // YDD
  25747: "YIDU Smart Technology Beijing, China", // YDS
  25773: "KYENM TECH, India", // YEM
  25795: "Yufeng Changhui Automation Instrument, China", // YFC
  25837: "YGM Shandong Yiguang heat metering technology, China", // YGM
  25861: "Youho Electric, South Korea", // YHE
  25862: "Hebei Haifeng Electronic Technology, China", // YHF
  25946: "Zhuhai Yujian Science Technology, China", // YJZ
  26053: "YOONO ENERGY TECHNOLOGY JIANGSU, China", // YNE
  26064: "Ningbo Yong Neng Power Technology, China", // YNP
  26128: "YPP, South Korea", // YPP
  26227: "Yellowstone Soft, Germany", // YSS
  26245: "Yuksek Teknoloji, Turkey", // YTE
  26252: "ZheJiang yongtailong electronic, China", // YTL
  26423: "Shandong youyuan instrument, China", // YYW
  26450: "Cangzhou City Hebei Electronic Technology, China", // YZR
  26663: "Zellweger Uster, Switzerland", // ZAG
  26672: "Zaptronix", // ZAP
  26674: "SNC ZARALAB, Bulgaria", // ZAR
  26728: "Zhejiang Chaorong Electric Technology, China", // ZCH
  26741: "Suzhou Dojustek Intelligent Technology, China", // ZCU
  26796: "Dr techn Josef Zelisko, Austria", // ZEL
  26798: "ZenMeter Solutions, India", // ZEN
  26808: "ZEXON ENERGY, India", // ZEX
  26841: "Hang Zhou Fu Yang Instrument General Factory, China", // ZFY
  26872: "ZIGNUX TECHNOLOGY, Spain", // ZGX
  26928: "St Petersburg Meters Factory, Russian Federation", // ZIP
  26934: "ZIV Aplicaciones y Tecnologia", // ZIV
  26969: "Zhejiang Jiayou Thermal Technology Equipment, China", // ZJY
  27031: "Ningbo ZLINK Technology, China", // ZLW
  27124: "Zhejiang Ocaenergy Technology", // ZOT
  27137: "ZPA Smart Energy, Czech Republic", // ZPA
  27170: "Zhejiang Qibin Technology, China", // ZQB
  27209: "ZENNER International, Germany", // ZRI
  27213: "ZENNER International, Germany", // ZRM
  27269: "ZTE Corporation ZTE Plaza, China", // ZTE
  27288: "ZHEJIANG TANCY INSTRUMENT TECHNOLOGY eTD, China", // ZTX
  27289: "ZHEJIANG CHINT INSTRUMENT METER, China", // ZTY
  27331: "SigmaHeat", // ZVC
  27412: "Zhejiang Xinghao Technology", // ZXT
  27417: "Linyi City Xiaoyuan Water Meter, China", // ZXY
  27426: "WEIHAI ZHENYU INTELL TECH, China", // ZYB
  27443: "Wuxi Zhongyi Smart Technology, China", // ZYS
  27482: "Michael Rac, Germany", // ZZZ
});
