// Kamstrup Multical 302/303/403/602/603/803 heat meter driver.
//
// Port of vendor/wmbusmeters@af48083/drivers/src/kamheat.xmq (declarative
// subset — full 30+ status bit names + extras-fields deferred).

import { flagToManufacturer } from "../../protocol/manufacturers.js";
import { defineDriver } from "../registry.js";

const KAM = flagToManufacturer("KAM");

export const kamheat = defineDriver({
  name: "kamheat",
  aliases: [
    "multical302",
    "multical303",
    "multical403",
    "multical602",
    "multical603",
    "multical803",
  ],
  meterType: "HeatMeter",
  linkModes: ["C1", "T1"],
  mvt: [
    { manufacturer: KAM, version: 0x30, type: 0x04 },
    { manufacturer: KAM, version: 0x30, type: 0x0d },
    { manufacturer: KAM, version: 0x30, type: 0x0c },
    { manufacturer: KAM, version: 0x40, type: 0x04 },
    { manufacturer: KAM, version: 0x40, type: 0x0c },
    { manufacturer: KAM, version: 0x19, type: 0x04 },
    { manufacturer: KAM, version: 0x34, type: 0x04 },
    { manufacturer: KAM, version: 0x34, type: 0x0a },
    { manufacturer: KAM, version: 0x34, type: 0x0b },
    { manufacturer: KAM, version: 0x34, type: 0x0c },
    { manufacturer: KAM, version: 0x34, type: 0x0d },
    { manufacturer: KAM, version: 0x1c, type: 0x04 },
    { manufacturer: KAM, version: 0x35, type: 0x04 },
    { manufacturer: KAM, version: 0x35, type: 0x0c },
    { manufacturer: KAM, version: 0x39, type: 0x04 },
  ],
  defaultFields: "name,id,total_energy_consumption_kwh,total_volume_m3,status,timestamp",
  libraryFields: [
    "fabrication_no",
    "meter_date",
    "meter_datetime",
    "on_time_h",
    "on_time_at_error_h",
    "flow_return_temperature_difference_c",
    "target_date",
  ],
  fields: [
    {
      kind: "string",
      name: "status",
      description: "Status and error flags.",
      properties: ["STATUS", "INCLUDE_TPL_STATUS"],
      match: { difVifKey: "04FF22" },
      lookup: {
        rules: [
          {
            name: "ERROR_FLAGS",
            mapType: "BitToString",
            maskBits: 0xffffffff,
            defaultMessage: "OK",
            map: [
              { value: 0x00000001, text: "VOLTAGE_INTERRUPTED" },
              { value: 0x00000002, text: "LOW_BATTERY_LEVEL" },
              { value: 0x00000004, text: "SENSOR_ERROR" },
              { value: 0x00000008, text: "SENSOR_T1_ABOVE_MEASURING_RANGE" },
              { value: 0x00000010, text: "SENSOR_T2_ABOVE_MEASURING_RANGE" },
              { value: 0x00000020, text: "SENSOR_T1_BELOW_MEASURING_RANGE" },
              { value: 0x00000040, text: "SENSOR_T2_BELOW_MEASURING_RANGE" },
              { value: 0x00000080, text: "TEMP_DIFF_WRONG_POLARITY" },
              { value: 0x00000100, text: "FLOW_SENSOR_WEAK_OR_AIR" },
              { value: 0x00000200, text: "WRONG_FLOW_DIRECTION" },
              { value: 0x00000800, text: "FLOW_INCREASED" },
              { value: 0x00001000, text: "IN_A1_LEAKAGE_IN_THE_SYSTEM" },
              { value: 0x00002000, text: "IN_B1_LEAKAGE_IN_THE_SYSTEM" },
              { value: 0x00004000, text: "IN_A1_A2_EXTERNAL_ALARM" },
              { value: 0x00008000, text: "IN_B1_B2_EXTERNAL_ALARM" },
            ],
          },
        ],
      },
    },
    {
      kind: "numeric",
      name: "total_energy_consumption",
      description: "Total heat energy consumption.",
      quantity: "Energy",
      scaling: "Auto",
      signedness: "Signed",
      match: { measurementType: "Instantaneous", vifRange: "AnyEnergyVIF" },
    },
    {
      kind: "numeric",
      name: "total_volume",
      description: "Total volume of heating media.",
      quantity: "Volume",
      scaling: "Auto",
      signedness: "Signed",
      match: { measurementType: "Instantaneous", vifRange: "Volume" },
    },
    {
      kind: "numeric",
      name: "volume_flow",
      description: "Current volume flow.",
      quantity: "Flow",
      scaling: "Auto",
      signedness: "Signed",
      match: { measurementType: "Instantaneous", vifRange: "VolumeFlow" },
    },
    {
      kind: "numeric",
      name: "power",
      description: "Current power.",
      quantity: "Power",
      scaling: "Auto",
      signedness: "Signed",
      match: { measurementType: "Instantaneous", vifRange: "AnyPowerVIF" },
    },
    {
      kind: "numeric",
      name: "flow_temperature",
      description: "Flow (supply) temperature.",
      quantity: "Temperature",
      scaling: "Auto",
      signedness: "Signed",
      match: { measurementType: "Instantaneous", vifRange: "FlowTemperature" },
    },
    {
      kind: "numeric",
      name: "return_temperature",
      description: "Return temperature.",
      quantity: "Temperature",
      scaling: "Auto",
      signedness: "Signed",
      match: { measurementType: "Instantaneous", vifRange: "ReturnTemperature" },
    },
    {
      kind: "numeric",
      name: "max_power",
      description: "Maximum power observed.",
      quantity: "Power",
      scaling: "Auto",
      signedness: "Signed",
      match: { measurementType: "Maximum", vifRange: "AnyPowerVIF" },
    },
    {
      kind: "numeric",
      name: "max_volume_flow",
      description: "Maximum volume flow observed.",
      quantity: "Flow",
      scaling: "Auto",
      signedness: "Signed",
      match: { measurementType: "Maximum", vifRange: "VolumeFlow" },
    },
    {
      kind: "numeric",
      name: "max_flow_temperature",
      description: "Maximum flow temperature observed.",
      quantity: "Temperature",
      scaling: "Auto",
      signedness: "Signed",
      match: { measurementType: "Maximum", vifRange: "FlowTemperature" },
    },
    {
      kind: "numeric",
      name: "max_return_temperature",
      description: "Maximum return temperature observed.",
      quantity: "Temperature",
      scaling: "Auto",
      signedness: "Signed",
      match: { measurementType: "Maximum", vifRange: "ReturnTemperature" },
    },
    {
      kind: "numeric",
      name: "target_energy_consumption",
      description: "Energy at end of last billing period.",
      quantity: "Energy",
      scaling: "Auto",
      signedness: "Signed",
      match: {
        measurementType: "Instantaneous",
        vifRange: "AnyEnergyVIF",
        storageNr: 1,
      },
    },
    {
      kind: "numeric",
      name: "target_volume",
      description: "Volume at end of last billing period.",
      quantity: "Volume",
      scaling: "Auto",
      signedness: "Signed",
      match: { measurementType: "Instantaneous", vifRange: "Volume", storageNr: 1 },
    },
  ],
});
