// Generate the manufacturer name lookup table from upstream manufacturers.h.
//
// Run once, or whenever the vendored wmbusmeters commit moves:
//   npx tsx scripts/generate-manufacturers.ts
//
// Writes `src/protocol/manufacturer-names.ts` — a single constant mapping
// 16-bit manufacturer codes to human-readable names, ~1540 entries.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const SRC = join(REPO_ROOT, "vendor", "wmbusmeters@af48083", "src", "manufacturers.h");
const OUT = join(REPO_ROOT, "src", "protocol", "manufacturer-names.ts");

function manfCode(a: string, b: string, c: string): number {
  return (a.charCodeAt(0) - 64) * 1024 + (b.charCodeAt(0) - 64) * 32 + (c.charCodeAt(0) - 64);
}

const content = readFileSync(SRC, "utf8");
const entryRe = /^X\(([A-Z]{3}),MANFCODE\('([A-Z])','([A-Z])','([A-Z])'\),"([^"]*)"\)\\?$/gm;

// Upstream manufacturers.h has a handful of duplicate MANFCODE rows
// (e.g. two KFM entries, two NAS entries). Upstream's linear-search
// lookup returns the first match, so we keep the first occurrence and
// silently drop the rest — matches C++ behaviour.
const byCode = new Map<number, { flag: string; code: number; name: string }>();
for (const match of content.matchAll(entryRe)) {
  const [, flag, a, b, c, name] = match;
  if (!flag || !a || !b || !c || name === undefined) continue;
  const code = manfCode(a, b, c);
  if (!byCode.has(code)) {
    byCode.set(code, { flag, code, name });
  }
}
const entries = [...byCode.values()].sort((a, b) => a.code - b.code);

const lines: string[] = [
  "// Auto-generated by scripts/generate-manufacturers.ts — do not edit by hand.",
  "// Source: vendor/wmbusmeters@af48083/src/manufacturers.h",
  "//",
  "// Maps 16-bit manufacturer codes (MANFCODE packing of 3 upper-case letters) to",
  "// the human-readable name upstream wmbusmeters assigns. The 3-letter flag can",
  "// be computed directly from the code — see `manufacturerFlag()` in manufacturers.ts.",
  "",
  "export const MANUFACTURER_NAMES: Readonly<Record<number, string>> = Object.freeze({",
];
for (const e of entries) {
  const escaped = e.name.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  lines.push(`  0x${e.code.toString(16).padStart(4, "0")}: "${escaped}", // ${e.flag}`);
}
lines.push("});", "");

writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(`Generated ${entries.length} manufacturer entries → ${OUT}`);
